version: 2

project_name: eightctl

changelog:
  disable: true

builds:
  - id: eightctl
    main: ./cmd/eightctl
    binary: eightctl
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - builds:
      - eightctl
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
